# Programming for Data Science Series (Lab Session 14)
## Numpy Operations & Functions
### Objectives
* To understand different way of creating Numpy Array (with pre-populated data options)
* Array calculations and math operations between two Numpy arrays
* Useful Statistical functions in Numpy Library
* Working with Files in Numpy (Reading & Writing)

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

<b>The following code demonstrate different ways of creating Numpy arrays</b>

In [2]:
b = np.arange(1, 10, 2)
b

array([1, 3, 5, 7, 9])

In [3]:
c = np.linspace(1, 10, 5)
c

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [4]:
d = np.zeros((2,2))
d

array([[0., 0.],
       [0., 0.]])

In [5]:
e = np.ones((3,3))
e

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
f = np.full((5,), 7)
f

array([7, 7, 7, 7, 7])

In [10]:
g = np.full((5,2), 7)
g

array([[7, 7],
       [7, 7],
       [7, 7],
       [7, 7],
       [7, 7]])

In [11]:
h = np.fromstring('5 10 15 20 25', dtype=np.int, sep=' ')
h

array([ 5, 10, 15, 20, 25])

In [13]:
np.around([0.37, 1.64, 1.5, 1.49])

array([0., 2., 2., 1.])

In [14]:
np.around([0.37, 1.64, 1.5, 1.49], decimals=1)

array([0.4, 1.6, 1.5, 1.5])

<b>Note: The following code will rounds to nearest even value</b>

In [15]:
np.around([.5, 1.5, 2.5, 3.5, 4.5])

array([0., 2., 2., 4., 4.])

In [17]:
a

array([1, 2, 3, 4, 5])

In [18]:
a.sum()

15

<b>Note: For two dimensional array, sum() method will add respective element from each array</b>

In [26]:
a = np.array([[1,2,3],[4,5,6]])
a.sum()

21

<b>Note: When axis set to zero, sum() method will sum up each columns, i.e. 1+4, 2+5, 3+6</b>

In [29]:
a.sum(axis=0)

array([5, 7, 9])

<b>Note: When axis set to one, sum() method will sum up each array, i.e. 1+2+3, 4+5+6</b>

In [34]:
a.sum(axis=1)

array([ 6, 15])

### Mathematical/Statistical Functions
* a.min() - get minimum value
* a.max() - get maximum value
* a.mean() - get mean value
* a.var() - get variance
* a.std() - get standard deviation
* a.argmin() - get index of minimum element
* a.argmax() - get index of maximum element

In [46]:
price = np.array([350,500,400,250,150])
print('min value: ', price.min())
print('max value: ', price.max())
print('mean value: ', price.mean())
print('var value: ', price.var())
print('std value: ', price.std())

min value:  150
max value:  500
mean value:  330.0
var value:  14600.0
std value:  120.83045973594572


In [47]:
print(price)
price.argmin()

[350 500 400 250 150]


4

In [48]:
price.argmax()

1

### Reading & Writing to Files
Below section will demonstrate two basic operation relating to files
* Load text file data
* Write/Save data to text file

In [51]:
textData = np.loadtxt('data.txt', skiprows=1, delimiter=',', dtype=np.int32)
textData

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  3,  5,  7, 11],
       [ 2,  4,  8, 16, 32]])

In [52]:
textData = np.genfromtxt('data.txt', skip_header=1, delimiter=',', dtype=np.int32)
textData

array([[ 1,  2,  3,  4,  5],
       [ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 2,  3,  5,  7, 11],
       [ 2,  4,  8, 16, 32]])

In [53]:
type(textData[0][1])

numpy.int32

In [56]:
multiplyFive = textData * 5
multiplyFive

array([[  5,  10,  15,  20,  25],
       [  5,  15,  25,  35,  45],
       [ 10,  20,  30,  40,  50],
       [ 10,  15,  25,  35,  55],
       [ 10,  20,  40,  80, 160]])

In [62]:
np.savetxt('new_data.txt', multiplyFive, delimiter=',', fmt='%d', header='c1,c3,c3,c4,c5', comments='')